/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cabinetmédical;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;
import com.raven.datechooser.DateChooser;
import javax.swing.JOptionPane;
/**
 *
 * @author iguer
 */
public class RendezVous extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    DateChooser chdate = new DateChooser ();

    /**
     * Creates new form RendezVous
     */
    public RendezVous() {
        initComponents();
        table();
        chdate.setTextField(date);
        chdate.setDateSelectionMode(DateChooser.DateSelectionMode.SINGLE_DATE_SELECTED);
        chdate.setLabelCurrentDayVisible(false);
    }
    
    
     public void Connect (){ 
        try {
           Class.forName("org.sqlite.JDBC");
         con = DriverManager.getConnection("jdbc:sqlite:cabinet.db");
        }
        catch (Exception e){
          e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtprenom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        rechercher = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        supprimer = new javax.swing.JButton();
        actualiser = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idp = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        heure = new javax.swing.JTextField();
        RETOUR = new javax.swing.JButton();
        statut = new javax.swing.JComboBox<>();
        quitter = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153), new java.awt.Color(0, 204, 153)), "Recherche RendezVous", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36), new java.awt.Color(0, 204, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 153));
        jLabel1.setText("Recherche avec Nom et Prénom :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 250, 31));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setToolTipText("");
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setName("RendezVous"); // NOI18N
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTable1MouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 490, 120));
        jPanel1.add(txtprenom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 101, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 153));
        jLabel3.setText("Nom :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 50, 18));

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 153));
        jLabel4.setText("Prénom :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 70, -1));
        jPanel1.add(txtnom, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 101, -1));

        rechercher.setBackground(new java.awt.Color(0, 204, 153));
        rechercher.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        rechercher.setForeground(new java.awt.Color(255, 255, 255));
        rechercher.setText("Rechercher");
        rechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercherActionPerformed(evt);
            }
        });
        jPanel1.add(rechercher, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 170, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cabinetmédical/rdv1.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 570, 350));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, 280, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 400));

        jPanel7.setBackground(new java.awt.Color(0, 204, 153));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "Fiche RendezVous", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        supprimer.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        supprimer.setForeground(new java.awt.Color(0, 204, 153));
        supprimer.setText("Supprimer");
        supprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerActionPerformed(evt);
            }
        });
        jPanel7.add(supprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 150, -1, -1));

        actualiser.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        actualiser.setForeground(new java.awt.Color(0, 204, 153));
        actualiser.setText("Actualiser");
        actualiser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualiserActionPerformed(evt);
            }
        });
        jPanel7.add(actualiser, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, 124, -1));

        modifier.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        modifier.setForeground(new java.awt.Color(0, 204, 153));
        modifier.setText("Modifier");
        modifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierActionPerformed(evt);
            }
        });
        jPanel7.add(modifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 124, -1));

        jLabel6.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ID Patient");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date RDV");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 90, 30));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Heure RDV");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 110, 30));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(" Statut ");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 90, 30));

        idp.setBackground(new java.awt.Color(204, 255, 255));
        idp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpActionPerformed(evt);
            }
        });
        jPanel7.add(idp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 30));

        date.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 110, 30));

        heure.setBackground(new java.awt.Color(204, 255, 255));
        jPanel7.add(heure, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 110, 30));

        RETOUR.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        RETOUR.setForeground(new java.awt.Color(0, 204, 153));
        RETOUR.setText("RETOUR");
        RETOUR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RETOURActionPerformed(evt);
            }
        });
        jPanel7.add(RETOUR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 180, 40));

        statut.setBackground(new java.awt.Color(204, 255, 255));
        statut.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        statut.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En Attente", "Passé" }));
        statut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statutActionPerformed(evt);
            }
        });
        jPanel7.add(statut, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 120, 30));

        quitter.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        quitter.setForeground(new java.awt.Color(0, 204, 153));
        quitter.setText("QUITTER");
        quitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterActionPerformed(evt);
            }
        });
        jPanel7.add(quitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 180, 40));

        ajouter.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        ajouter.setForeground(new java.awt.Color(0, 204, 153));
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });
        jPanel7.add(ajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 124, -1));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 870, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//modifier les rdvs selectionnés à partir de la table
    private void modifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierActionPerformed
    try{ 
         Connect();
         pst = con.prepareStatement("UPDATE rendezvous set idp=?, date_rdv=?, heure_rdv=? ,statut=? "
                 + "where idrdv=?");
         int idrdv =jTable1.getSelectedRow();
         String selectionner = (String)jTable1.getValueAt(idrdv,0) ;
         pst.setString(1,idp.getText());
         pst.setString(2,date.getText());
         pst.setString(3,heure.getText());
         pst.setString(4,statut.getSelectedItem().toString());
         pst.setString(5,selectionner);
         pst.executeUpdate();
         con.close();
         table();
    } catch (Exception e) {
      e.printStackTrace();
    }
    }//GEN-LAST:event_modifierActionPerformed

    
    private void idpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpActionPerformed
       
    }//GEN-LAST:event_idpActionPerformed

    
  //actualiser le contenu des colonnes rdvs
    private void actualiserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualiserActionPerformed
        
        idp.setText("");
        date.setText("");
        heure.setText("");
       
        
    }//GEN-LAST:event_actualiserActionPerformed

    
    
//Retour à la fiche patient 
    private void RETOURActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RETOURActionPerformed
          RendezVous.super.dispose ();
          Patient P= new Patient();
          P.setVisible(true);
    }//GEN-LAST:event_RETOURActionPerformed

    
    private void statutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statutActionPerformed
        
    }//GEN-LAST:event_statutActionPerformed

    
    
    
    private void quitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterActionPerformed
        RendezVous.super.dispose ();
          Login L= new Login ();
          L.setVisible(true);
    }//GEN-LAST:event_quitterActionPerformed

    
 //Ajouter un rdv
    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
  
  try {
    // Se connecter à la base de données
    Connect();

    // Préparer l'instruction SQL pour insérer des données
    PreparedStatement pst = con.prepareStatement("INSERT INTO rendezvous (idp, date_rdv, heure_rdv, statut) VALUES (?, ?, ?, ?)");

    // Définir les valeurs pour l'instruction préparée en récupérant les valeurs des champs de texte
    pst.setString(1, idp.getText());
    pst.setString(2, date.getText());
    pst.setString(3, heure.getText());
    pst.setString(4,statut.getSelectedItem().toString());

    // Exécuter la requête de mise à jour
    pst.executeUpdate();
    
    // Mettre à jour le tableau (appeler votre méthode de tableau)
    table();
    
    JOptionPane.showMessageDialog(this, "Rendez-vous ajouté avec succès !", "Succès", JOptionPane.INFORMATION_MESSAGE);

  } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout du rendez-vous !", "Erreur", JOptionPane.ERROR_MESSAGE);
    e.printStackTrace();
  } finally {
    try {
      // Fermer la connexion
      con.close();
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
        
    }//GEN-LAST:event_ajouterActionPerformed

    
    
    private void supprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerActionPerformed
       try{
            Connect();
            pst = con.prepareStatement("Delete  from rendezvous where idrdv=?");
            int idpatient =jTable1.getSelectedRow();
            String selectionner = (String)jTable1.getValueAt(idpatient,0) ;
            pst.setString(1,selectionner);
            pst.executeUpdate();
            con.close();
            //JOptionPane.showMessageDialog(null," Patient supprimé avec succès");
            table();
        } catch (Exception e) {
            e.printStackTrace();
            //JOptionPane.showMessageDialog(null, "Erreur : Impossible de supprimer le patient\n" + e.getMessage());
        }
    }//GEN-LAST:event_supprimerActionPerformed

    
    
    
    
    
    private void jTable1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseReleased
        
    int select =jTable1.getSelectedRow();
      //model est la variable de la table
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
     
      idp.setText(model.getValueAt(select,1).toString() );
      date.setText(model.getValueAt(select,2).toString() );
      heure.setText(model.getValueAt(select,3).toString() );
      statut.setSelectedItem(model.getValueAt(select,4).toString() );
     
      
    }//GEN-LAST:event_jTable1MouseReleased

    
  //Rechercher dans la table
    private void rechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercherActionPerformed

    // Obtenir le nom et le prénom saisis
    String nom = txtnom.getText().toUpperCase();
    String prenom = txtprenom.getText().toUpperCase();

    try {
        // Se connecter à la base de données
        Connect();

        // Préparer la requête pour récupérer l'ID du patient
        PreparedStatement pstPatient = con.prepareStatement("SELECT idpatient FROM patient WHERE nom = ? AND prenom = ?");
        pstPatient.setString(1, nom);
        pstPatient.setString(2, prenom);

        // Exécuter la requête pour l'ID du patient
        ResultSet rsPatient = pstPatient.executeQuery();

        // Vérifier si un patient est trouvé
        if (rsPatient.next()) {
            int idPatient = rsPatient.getInt("idpatient");

            // Préparer la requête pour récupérer les rendez-vous du patient
            PreparedStatement pstRDV = con.prepareStatement("SELECT * FROM rendezvous WHERE idp = ?");
            pstRDV.setInt(1, idPatient);

            // Exécuter la requête pour les rendez-vous
            ResultSet rsRDV = pstRDV.executeQuery();

            // Vider le modèle de table actuel
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);

            // Ajouter les rendez-vous trouvés au modèle de table
            int selectedRowCount = 0; // Compteur de lignes sélectionnées
            while (rsRDV.next()) {
                Object[] row = {
                        rsRDV.getString("idrdv"), // Sélectionner l'ID du rendez-vous
                        rsRDV.getString("idp"),
                        rsRDV.getString("date_rdv"),
                        rsRDV.getString("heure_rdv"),
                        rsRDV.getString("statut")
                };
                model.addRow(row);
                selectedRowCount++;
            }

            // Sélectionner toutes les lignes ajoutées
            jTable1.setRowSelectionInterval(0, selectedRowCount - 1);

            // Afficher le message de confirmation
            JOptionPane.showMessageDialog(this, "Rendez-vous trouvés pour le patient : " + nom + " " + prenom, "Recherche réussie", JOptionPane.INFORMATION_MESSAGE);
             table();

        } else {
            // Afficher le message d'erreur si aucun patient n'est trouvé
            JOptionPane.showMessageDialog(this, "Aucun patient trouvé avec le nom et prénom spécifiés.", "Patient introuvable", JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de la recherche des rendez-vous.", "Erreur", JOptionPane.ERROR_MESSAGE);
    } finally {
        try {
            con.close();
        } catch (Exception e) {
            /* Gérer les erreurs de fermeture de la connexion */
        }
    }


    }//GEN-LAST:event_rechercherActionPerformed

 //méthode table
      public void table(){
        
        String [] rdv ={"ID Rdv","ID Patient","Date Rdv","Heure Rdv","Statut"};
              DefaultTableModel model = new DefaultTableModel (rdv,0);
              
              
        try { Connect();
         PreparedStatement pst = con.prepareStatement("Select * from rendezvous ");
          rs = pst.executeQuery();
         while(rs.next()){
            Object[] row ={
           rs.getString("idrdv"),
           rs.getString("idp"),
           rs.getString("date_rdv"),
           rs.getString("heure_rdv"),
           rs.getString("statut")
            };
            model.addRow(row); }
         jTable1.setModel(model);
        } catch(Exception e){
            e.printStackTrace();
        }
      }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RendezVous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RendezVous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RendezVous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RendezVous.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RendezVous().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RETOUR;
    private javax.swing.JButton actualiser;
    private javax.swing.JButton ajouter;
    private javax.swing.JTextField date;
    private javax.swing.JTextField heure;
    private javax.swing.JTextField idp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modifier;
    private javax.swing.JButton quitter;
    private javax.swing.JButton rechercher;
    private javax.swing.JComboBox<String> statut;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
